In [339]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [340]:
irisDataset = pd.read_csv('data_diabetes.csv',header=0)

In [341]:
irisDataset.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [342]:
print(irisDataset)

    Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0             6      148             72  ...                     0.627   50        1
1             1       85             66  ...                     0.351   31        0
2             8      183             64  ...                     0.672   32        1
3             1       89             66  ...                     0.167   21        0
4             0      137             40  ...                     2.288   33        1
..          ...      ...            ...  ...                       ...  ...      ...
95            6      144             72  ...                     0.255   40        0
96            2       92             62  ...                     0.130   24        0
97            1       71             48  ...                     0.323   22        0
98            6       93             50  ...                     0.356   23        0
99            1      122             90  ...                     

In [343]:
irisDataset = irisDataset.drop(labels="BMI",axis=1)
irisDataset = irisDataset.drop(labels="DiabetesPedigreeFunction",axis=1)
irisDataset = irisDataset.drop(labels="Age",axis=1)

In [344]:
print(irisDataset)

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  Outcome
0             6      148             72             35        0        1
1             1       85             66             29        0        0
2             8      183             64              0        0        1
3             1       89             66             23       94        0
4             0      137             40             35      168        1
..          ...      ...            ...            ...      ...      ...
95            6      144             72             27      228        0
96            2       92             62             28        0        0
97            1       71             48             18       76        0
98            6       93             50             30       64        0
99            1      122             90             51      220        1

[100 rows x 6 columns]


In [345]:
irisDataset = irisDataset.to_numpy()

In [346]:
print(irisDataset)

[[  6 148  72  35   0   1]
 [  1  85  66  29   0   0]
 [  8 183  64   0   0   1]
 [  1  89  66  23  94   0]
 [  0 137  40  35 168   1]
 [  5 116  74   0   0   0]
 [  3  78  50  32  88   1]
 [ 10 115   0   0   0   0]
 [  2 197  70  45 543   1]
 [  8 125  96   0   0   1]
 [  4 110  92   0   0   0]
 [ 10 168  74   0   0   1]
 [ 10 139  80   0   0   0]
 [  1 189  60  23 846   1]
 [  5 166  72  19 175   1]
 [  7 100   0   0   0   1]
 [  0 118  84  47 230   1]
 [  7 107  74   0   0   1]
 [  1 103  30  38  83   0]
 [  1 115  70  30  96   1]
 [  3 126  88  41 235   0]
 [  8  99  84   0   0   0]
 [  7 196  90   0   0   1]
 [  9 119  80  35   0   1]
 [ 11 143  94  33 146   1]
 [ 10 125  70  26 115   1]
 [  7 147  76   0   0   1]
 [  1  97  66  15 140   0]
 [ 13 145  82  19 110   0]
 [  5 117  92   0   0   0]
 [  5 109  75  26   0   0]
 [  3 158  76  36 245   1]
 [  3  88  58  11  54   0]
 [  6  92  92   0   0   0]
 [ 10 122  78  31   0   0]
 [  4 103  60  33 192   0]
 [ 11 138  76   0   0   0]
 

In [355]:
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]),
                              axis=0)

In [356]:
print(dataTesting)
len(dataTesting)

[[  3 180  64  25  70   0]
 [  7 133  84   0   0   0]
 [  7 106  92  18   0   0]
 [  9 171 110  24 240   1]
 [  7 159  64   0   0   0]
 [  0 180  66  39   0   1]
 [  1 146  56   0   0   0]
 [  2  71  70  27   0   0]
 [  7 103  66  32   0   1]
 [  7 105   0   0   0   0]
 [  1  80  55   0   0   0]
 [  4 123  80  15 176   0]
 [  7  81  78  40  48   0]
 [  4 134  72   0   0   1]
 [  2 142  82  18  64   0]
 [  6 144  72  27 228   0]
 [  2  92  62  28   0   0]
 [  1  71  48  18  76   0]
 [  6  93  50  30  64   0]
 [  1 122  90  51 220   1]]


20

In [357]:
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 5]
labelTesting = dataTesting[:, 5]
print(labelTraining)
len(labelTraining)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 0 1 0]


80

In [358]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
from sklearn import tree
import matplotlib.pyplot as plt

In [359]:
model = tree.DecisionTreeClassifier()

In [360]:
model = model.fit(inputTraining, labelTraining)

In [361]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1]
Hasil Prediksi :  [1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1]


In [362]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) *100,"%")

Prediksi Benar :  13 data
Prediksi Salah :  7 data
Akurasi :  65.0 %
